### ISSUE TITLE
BSON::InvalidKeyName not caught on #update

### ISSUE THREAD

**Issue by brasic** [solnic/dm-mongo-adapter#19]
BSON rejects hash keys with periods.  When you try to BSON-serialize a ruby Hash containing illegal keys, `BSON::InvalidKeyName` should be raised.   When creating a new DataMapper::Mongo::Resource containing such a hash, the error is handled correctly:

``` ruby
class Sample
  include DataMapper::Mongo::Resource
  property :id, ObjectId
  property :data, Hash
end
DataMapper.finalize

invalid_hash = {'bad.key' => 1}
valid_hash = {'good_key' => 1}

Sample.create(:data => invalid_hash)
#=> BSON::InvalidKeyName: bad.key - key must not contain '.'
```

But if we create a valid resource then later update it with an invalid hash, the failure is silently dropped.
The resource appears to have been persisted, even though Mongo never accepted the data:

``` ruby
a = Sample.create(:data => valid_hash)
#=> #<Sample @id=BSON::ObjectId('4fce0d32faa3171f99000004') @data={"good_key"=>1}>

a.update(:data => invalid_hash)
#=> true

a.data
#=> {"bad.key"=>1}

a.persisted?
#=> true

a.dirty?
#=> false

b = Sample.first
#=> #<Sample @id=BSON::ObjectId('4fce0d32faa3171f99000004') @data={:good_key=>1}>

a == b
=> true
```

**Comment by mbj** [comment]
Can you test what happens if you set :safe => true in the DataMapper.setup options hash? The mongo gem should raise if the mongodb does not accept an invalid operation. Updates should hit the bson serialization too, currently I do not know why there was no error raised in the update case.

Do you have time to create an executable example?

**Comment by brasic** [comment]
I'll have to get back to you.  When I tried to extract this into an executable example with the latest copy of the gem, the bad hash is actually getting persisted to mongo, which I didn't think was possible.

**Comment by brasic** [comment]
Closing this, `:safe => true` works for me.
