### ISSUE TITLE
EmbeddedResources cannot have complex properties or embedments

### ISSUE THREAD

**Issue by rkilian** [solnic/dm-mongo-adapter#3]
Defining a property of type Hash or Array in an embedded document causes the following error: "[...] property.rb: `initialize': +type+ was Hash, which is not a supported type (ArgumentError)".

And it would be nice to chain embedded documents, but the method "embeds" is not defined for an EmbeddedResource.

Thank you, this really rocks (-;

**Comment by myobie** [comment]
For the time being, once can use DataMapper::Mongo::Types::EmbeddedHash as a property type. However, it would be really nice if these types were imported into the EmbeddedResource as well.
