### ISSUE TITLE
Not compatible with the latest versions of dm-core?

### ISSUE THREAD

**Issue by jkp** [solnic/dm-mongo-adapter#4]
I'm having trouble using the mongo adapter now that I have gem installed dm-migrations.  This seems to have installed a newer version of dm-core and out of the box this doesn't seem to be compatible. 

I managed to make it install by changing the requirements in the Rakefile and changing line 182 of query.rb.  It declared a method with the method name on the next line, which seems wrong, but then I'm a ruby noob so I could just not understand some language feature you were using.

**Comment by solnic** [comment]
I'll be releasing a DM 1.0.0-compatible version within a week, the problems you're having will go away.

**Comment by jkp** [comment]
Great...

Question: how far along are you with ActiveModel compatibility?

**Comment by solnic** [comment]
As far as I know ActiveModel compatibility is implemented in dm-rails gem and it's finished. Basically DataMapper should be compatible with AM no matter what adapter you're using.
