### ISSUE TITLE
Finalize under dm-rails

### ISSUE THREAD

**Issue by juggy** [solnic/dm-mongo-adapter#5]
Hello,

I created a fresh rails 3.0 app with dm-rails and I am trying to use mongo-adapter. Here is what I get:

/Users/juggy/.rvm/gems/ruby-1.8.7-p174/gems/dm-core-1.0.0/lib/dm-core.rb:327:in `finalize_model': DataMapper::Mongo::EmbeddedResource must have at least one property or many to one relationship to be valid (DataMapper::IncompleteModelError)
    from /Users/juggy/.rvm/gems/ruby-1.8.7-p174/gems/dm-core-1.0.0/lib/dm-core.rb:309:in`finalize'
    from /Users/juggy/.rvm/gems/ruby-1.8.7-p174/gems/dm-core-1.0.0/lib/dm-core/model/descendant_set.rb:33:in `each'
    from /Users/juggy/.rvm/gems/ruby-1.8.7-p174/gems/dm-core-1.0.0/lib/dm-core/model/descendant_set.rb:33:in`each'
    from /Users/juggy/.rvm/gems/ruby-1.8.7-p174/gems/dm-core-1.0.0/lib/dm-core.rb:308:in `finalize'
    from /Users/juggy/.rvm/gems/ruby-1.8.7-p174/gems/dm-rails-1.0.0/lib/dm-rails/setup.rb:43:in`finalize'
    from /Users/juggy/.rvm/gems/ruby-1.8.7-p174/gems/dm-rails-1.0.0/lib/dm-rails/setup.rb:50:in `preload_models'
    from /Users/juggy/.rvm/gems/ruby-1.8.7-p174/gems/dm-rails-1.0.0/lib/dm-rails/railtie.rb:83:in`_callback_before_7'
    from /Users/juggy/.rvm/gems/ruby-1.8.7-p174/gems/activesupport-3.0.0.beta4/lib/active_support/callbacks.rb:423:in `_run_prepare_callbacks'

I have a single Mongo::Resource defined, no EmbeddedResource. When I do create an EmbeddedResource, it then seems to work.

I use the git master as the gem to run this.

Thanks,
Julien.

**Comment by solnic** [comment]
Unfortunately Embedments are not compatible with DM 1.0.0. There's a branch http://github.com/solnic/dm-mongo-adapter/tree/no_embedments which works fine although, as name states, it has Embedments completely removed. I'm going to make a new release soon (later this month) which will work with DM 1.0.0 but there won't be support for embedded documents in that release. It will be restored in much better form once EmbeddedValue is implemented in the dm-core (later this summer).
