### ISSUE TITLE
execute db.auth

### ISSUE THREAD

**Issue by iRonin** [solnic/dm-mongo-adapter#6]
Hello,

How can I execute mongo's db.auth with your adapter?

I think it shouldn't be necessary but for some reasons I keep getting:
cursor.rb:86:in `next_document': unauthorized db:db_name lock type:-1 client:127.0.0.1 (Mongo::OperationFailure)

Thanks!

**Comment by solnic** [comment]
During next month I will be working on a new version of the adapter which will work with DataMapper 1.1 (which is currently going through RC series) and I will look into that issue.

**Comment by iRonin** [comment]
Ok, looking forward to it!

**Comment by solnic** [comment]
ok today I pushed version 0.6.0. please check if it works for you :)
